version: "3.7"

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: avby-django:dev
    environment:
      DJANGO_SETTINGS_MODULE: avby.settings.settings
    env_file:
      - .env
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./avby:/usr/src/app/

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mailcatcher:
    image: dockage/mailcatcher:0.7.1
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres_data:


